export PATH="$HOME/.rbenv/bin:$PATH"
export TERM="xterm-color"

export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LANG="en_US.UTF-8"

eval "$(rbenv init -)"

[ -f ~/.bashrc ] && source ~/.bashrc
