" Vundle (Plugins)
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'jpo/vim-railscasts-theme'
Plugin 'Buffergator'
Plugin 'nerdtree'

call vundle#end()            " required
filetype plugin indent on    " required

"execute pathogen#infect()

if filereadable(expand("~/.vimrc.after"))
  source ~/.vimrc.after
endif
