" Vundle (Plugins)
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'jpo/vim-railscasts-theme'
Plugin 'Buffergator'
Plugin 'scrooloose/nerdtree'
Plugin 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}
Plugin 'w0ng/vim-hybrid'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'godlygeek/tabular.git'
Plugin 'tommcdo/vim-lion'
Plugin 'AndrewRadev/splitjoin.vim'
Plugin 'nanotech/jellybeans.vim' 
Plugin 'altercation/vim-colors-solarized'
Plugin 'flazz/vim-colorschemes'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

":PluginInstall \vi

call vundle#end()            " required
filetype plugin indent on    " required

"execute pathogen#infect()

if filereadable(expand("~/.vimrc.after"))
  source ~/.vimrc.after
endif
