call plug#begin()

Plug 'gmarik/Vundle.vim'
Plug 'jpo/vim-railscasts-theme'
Plug 'jeetsukumaran/vim-buffergator'
Plug 'scrooloose/nerdtree'
Plug 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}
Plug 'w0ng/vim-hybrid'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'tommcdo/vim-lion'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'nanotech/jellybeans.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'flrnprz/plastic.vim'
Plug 'sainnhe/edge'
Plug 'haishanh/night-owl.vim'
Plug 'skalnik/vim-vroom'
Plug 'csexton/trailertrash.vim'
Plug 'ap/vim-buftabline'
Plug 'Yggdroot/indentLine'
Plug 'elixir-editors/vim-elixir'
Plug 'joukevandermaas/vim-ember-hbs'
Plug 'joshdick/onedark.vim'
Plug 'arcticicestudio/nord-vim'
Plug 'fatih/vim-go'
Plug 'meain/vim-startify'
Plug 'udalov/kotlin-vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-rails'
Plug 'embark-theme/vim'
Plug 'nathanaelkane/vim-indent-guides'
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'sheerun/vim-polyglot'
Plug 'ghifarit53/tokyonight-vim'

call plug#end()

" :PlugInstall

if filereadable(expand("~/.vimrc.after"))
  source ~/.vimrc.after
endif

